version: '2'
services:
  ruby:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "9004:3000"