version: "2"
services:
  python:
    image: "python:3.7-alpine"
    working_dir: /home/python/app
    environment:
      - FLASK_APP=init.py
    volumes:
      - ./:/home/python/app
    expose:
      - "9002"
    ports:
      - "9002:5000"
    command: ash -c "pip install -r requirements.txt && python -m flask run --host=0.0.0.0"